### ISSUE TITLE
Send and recognize non-text messages

### ISSUE THREAD

**Issue by Leogomat** [rwth-acis/las2peer-social-bot-manager-service#13]
1. **Motivation** - The current social bot framework model does not allow a bot to send non-text messages (pdf or image files) as a response to an incoming chat message, not will it recognize incoming messages that are not of the type "text".

2. **Specification** - Extend the model so that it is possible to model chat responses containing non-text files. Also, implement the recognition of non-text chat messages by the bot. (conceptual idea [here](https://moodle.tech4comp.dbis.rwth-aachen.de/mod/forum/discuss.php?d=125#p225))

3. **Finalised state** - It is possible to model non-text responses and Bot is able to recognise incoming non-text messages.

**Comment by Aran30** [comment]
Possible as of release [1.1.0](https://github.com/rwth-acis/las2peer-social-bot-manager-service/releases/tag/1.1.0). Closing.
