### ISSUE TITLE
[BUG] Array out of bounds exception when submitting the bot model

### ISSUE THREAD

**Issue by Kusika** [rwth-acis/las2peer-social-bot-manager-service#132]
1. **Summary** - I started the service and trained a nlu model. However, when I click the Submit button in SBF I get an array out of bounds exception
2. **Bug Details**
   1. **What?** - Array out of bounds exception when uploading a bot to the service
   2. **Where?** - This affects the uploading of the bot model
   3. **When?/How often?** - This occurs every time I try to upload the model
   4. **How?/Current state** - Here is the exact error I get:
           There is something wrong with your bot model: {"code":500,"msg":"Index 1 out of bounds for length 1","stacktrace": 
           ["java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1"]}
   And here is the result I get from the service in the cli:
         Bot Botty registered at: [RSNH: <0x304C8F..>/PC/ip-string:9011]
         Messenger: Rocket.Chat
    I attached the bot model below as a txt file
[bot_model.txt](https://github.com/rwth-acis/las2peer-social-bot-manager-service/files/10056237/bot_model.txt)

P.S. Which rasa server version do I need to use with this service? I am using 2.8.16 right now, because 3.2 doesn't work.

**Comment by AlexanderNeumann** [comment]
Rasa version 2.8 should be fine. About the rest: @lakhoune can you check the model?

**Comment by lakhoune** [comment]
The bot model looks good to me as well. could you @Kusika could you maybe provide more information such as the stacktrace. Or the log file.

**Comment by Kusika** [comment]
I found the stacktrace [stacktrace.txt](https://github.com/rwth-acis/las2peer-social-bot-manager-service/files/10075756/stacktrace.txt). And here is the full log: [las2peer.log](https://github.com/rwth-acis/las2peer-social-bot-manager-service/files/10075807/las2peer.log)
I also noticed that the service doesn't save the model in the mysql database when I train the nlu model, but I don't know if that is actually a problem.

**Comment by phil-cd** [comment]
What "format" do you use for the `Authentication Token` in the RocketChat messenger in the bot model? I think it needs to be `<bot_username>:<bot_password>` and if the `:` is missing the ArrayIndexOutOfBoundsException may be thrown.

**Comment by lakhoune** [comment]
@phil-cd  you are right. @Kusika your authentication token is `test`. Looking at the stacktrace you see in [line 129](https://github.com/rwth-acis/las2peer-social-bot-manager-service/blob/8ea595c07f3ae4fad404e7024cfc57fb00a6e1c2/social-bot-manager/src/main/java/i5/las2peer/services/socialBotManagerService/chat/RocketChatMediator.java#L129)
throws the error because in your case you are accessing an array element that does not exist.
Funnily enough the method implementation also states as a todo error handling 😄

**Comment by lakhoune** [comment]
Yeah you can't use random tokens. You need to register the bot with rocket chat then rocket chat provides you with the token and you can then use that one

**Comment by Aran30** [comment]
Seems solved to me, closing.
