### ISSUE TITLE
Bot disconnects from Slack after a while

### ISSUE THREAD

**Issue by Manorhos** [rwth-acis/las2peer-social-bot-manager-service#2]
After an "unspecified amount of time", Slack sends a message with type "goodbye" and disconnects the client.
We need to handle this message and reconnect to Slack afterwards.

**Comment by PedeLa** [comment]
This was solved, right?

**Comment by Aran30** [comment]
> 
> 
> This was solved, right?

Did not happen since i've been working on the framework. So I think we can close.
