### ISSUE TITLE
[BUG] Telegram Bot creation fails

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/las2peer-social-bot-manager-service#206]
The current version of the bot manager service does not allow me to create bots for telegram messenger. The bug i encounter if I want to register my bot is that the telegram lib which parses the response when submitting the bot expects the id to be an integer, but receives a string. 
I think there might have been some changes to the telegram api

**Comment by nreinartz** [comment]
Since the bot id does no longer fit into an integer, the auth token cannot be parsed anymore. An update to the current version of the pengrad telegram bot fixes the issue.
