### ISSUE TITLE
Bot responds multiple times to single user message

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/las2peer-social-bot-manager-service#49]
1. **Summary** - The Bot sometimes responds to a single user message multiple times in the chat
2. **Bug Details** 
   1. **What?** - In some scenarios, when entering a message into the channel with the bot, the bot will respond to that message 2-3 times, as if the user had asked for it 2-3 times. It also advances the conversation flow (leadsTo)
   2. **Where?** - This issue for now mostly occured when a Bot Action with a call to a service is performed
   3. **When?/How often?** - The bug happends randomly, but I noticed that the probability of it happening increases, the longer the bot is deployed. When redeploying the bot, the issue seems to be gone for a while.
   4. **Examples** - 
![24-13_42_39_Slack _ mensabot _ Mensa Community](https://user-images.githubusercontent.com/38857665/112313757-804f3100-8ca8-11eb-991d-b36a5f9f4134.png)
![Image from iOS](https://user-images.githubusercontent.com/38857665/112314058-dc19ba00-8ca8-11eb-8506-42abb3076fa7.jpg)

**Comment by Aran30** [comment]
Has this still happened?  @lakhoune

**Comment by lakhoune** [comment]
I have not seen it occuring again

**Comment by lakhoune** [comment]
Maybe we should prevent this behavior to prevent confusion for users?

**Comment by Aran30** [comment]
> 
> 
> > Happens when you use the same auth token with different bot agent (defined by the bot name in the name attribute of the Bot Element)
> 
> how can I delete an existing bot then?

The [Bot Modelling Wiki](https://github.com/rwth-acis/Social-Bot-Framework/wiki) got updated accordingly to also explain how to delete bots. 
> 
> 
> Maybe we should prevent this behavior to prevent confusion for users?

A new issue (#87) was also created which precisely expains the next steps regarding this problem.
