### ISSUE TITLE
[BUG] Large bot models don't get stored

### ISSUE THREAD

**Issue by Aran30** [rwth-acis/las2peer-social-bot-manager-service#54]
1. **Summary** - Can't store large bot models (sorry, don't really have a definition for "large").
2. **Bug Details** 
   1. **What?** - When storing bot models in the modelling frontend. The error message found in the logs is: "Data truncation: Data too long for column 'model' at row 1"
   2. **Where?** - Use store function in modelling frontend to call models/store function of social bot manager.
   3. **When?/How often?** - When bot models start to become large (didn't investigate too much)

**Comment by Leogomat** [comment]
Note: for this fix to work in deployment, the 'models' MySQL table should be restarted
