### ISSUE TITLE
[ENH] Merge Telegram mediator

### ISSUE THREAD

**Issue by Leogomat** [rwth-acis/las2peer-social-bot-manager-service#60]
The sections for an enhancement issue are:

1. **Motivation** - In his Master thesis, Michael Crämer implemented a bot mediator for Telegram, which would be a good addition to the SBF.
2. **Specification** - The TelegramMediator class from Crämer's thesis and all its dependencies need to be merged into the develop branch.
3. **Finalised state** - The TelegramMediator class is merged into the develop branch and working correctly.

**Comment by dmonad** [comment]
Writing "closes #XX" or "fix #XX" in the commit or PR will automatically close the issue 😉

**Comment by Aran30** [comment]
> 
> 
> Writing "closes #XX" or "fix #XX" in the commit or PR will automatically close the issue 😉

Thanks for the info! 😄
