### ISSUE TITLE
[BUG] large message causes an "Internal server error".

### ISSUE THREAD

**Issue by Karlydiamond214** [rwth-acis/las2peer-social-bot-manager-service#65]
1. **Summary** - I have a service that sometimes returns long messages to users after computation.
2. **Bug Details** - A detailed explanation of the issue, structured in subsections:
   1. **What?** - the bot returns the message "Internal server error [500]" to the chat when the message that should be returned by a service is large 
   2. **Where?** - the error occurred when using the chat application "Rocket.chat" so I could not say if the same thing happens with other applications

**Comment by Aran30** [comment]
I changed the size of the possible rocket.chat messages a while back. Does the error still occur or not? Otherwise we can close this issue :) . @Karlydiamond214

**Comment by Karlydiamond214** [comment]
Yes I will do it.
Thank you for the Help
