### ISSUE TITLE
[BUG] Data in SBF tables gets deleted.

### ISSUE THREAD

**Issue by Leogomat** [rwth-acis/las2peer-social-bot-manager-service#72]
Since the last restart of the Social Bot Manager service, the data from the tables related to the SBF was lost, particularly the stored bot models and training data.

1. **Summary** - Something is causing the SBF tables to be reset. The reason is still inknown, but it is being investigated.
2. **Bug Details**:
   1. **What?** - The data in the SBF tables in MySQL gets deleted.
   2. **Where?** - MobSOS MySQL database in the sbf-dev namespace.
   3. **When?/How often?** - It is unknown when it occurs. It was first noticed on 12.07.2021.
   4. **How?/Current state** - Reproduction is unknown and is being investigated.
3. *(Optional)* **Fixed state** - SBF tables don't get reset.

**Comment by Leogomat** [comment]
The tables are probably getting reset by the "[SBF.sql](https://github.com/rwth-acis/las2peer-social-bot-manager-service/blob/master/SBF.sql)" file's "DROP TABLE IF EXISTS" statements.

**Comment by Leogomat** [comment]
However, the SQL file is only run by the "[docker-entrypoint.sh]"(https://github.com/rwth-acis/las2peer-social-bot-manager-service/blob/master/SBF.sql) script if the database given to the SBM does not contain the "MESSAGE" table (line 37). This check is wrong, because MESSAGE is not a SBF table, but rather a MobSOS table. I will fix the table name in a hotfix. However, this error does not seem to be the cause of the problem by itself, since the MySQL database used by the SBM in sbf-dev is also used by MobSOS and thus contains a "MESSAGE" table.

**Comment by Leogomat** [comment]
There was the suspicion that the tables got reset after every restart of the SBM service. However, the service was restarted about 16 hours ago and the SQL file was not run. This can be seen in the screenshot below ("Creating database schema..." message is missing).

![image](https://user-images.githubusercontent.com/22417560/125599218-edc02115-65b8-44f6-b0b4-29086cd98c5e.png)

**Comment by Aran30** [comment]
It seems that after the last restart everything was fine. Closing for now.
