### ISSUE TITLE
[BUG] Intent triggers wrong Bot Action

### ISSUE THREAD

**Issue by Taeuber-hub** [rwth-acis/las2peer-social-bot-manager-service#93]
When an intent was recognized, the wrong Bot Action, not the one defined in the frontend, was triggered.

After defining in the frontend modeling that intent "answer" triggers Bot Action "takingSurvey", the Bot Action "adminSurvey" was triggered after the intent "answer" was recognized. The correct intent was recognized, but the incorrect Bot Action was triggered.
The Social Bot Manager made the API call to an incorrect Bot Action. This occurred twice during a local deployment of the services.

The last fetched commit from the Social-Bot-Frontend: commit 7ac7e3532a8def5fd5528077de6b75fb7b8a425f
The last fetched commit from the Social Bot Manager: commit edf19195fca24208f6c82b9fa5fbcb7e07ecc713

**Comment by Aran30** [comment]
Please add your bot model so that I can look into it.

**Comment by Taeuber-hub** [comment]
The space is called surveybot, the same bot model is used in the cluster

**Comment by Aran30** [comment]
Didn't seem to occur again.
