### ISSUE TITLE
Bitbot/Feedbot show "submission succeeded" and "here is your feedback" messages at the same time or even in wrong order

### ISSUE THREAD

**Issue by SandraSchufmann** [rwth-acis/las2peer-social-bot-manager-service#98]
The two messages always appear at the same time, which does not make much sense. At one time they even appeared in the wrong order:

![image](https://user-images.githubusercontent.com/95752345/146189162-f93c23d4-d4fa-4e39-a78c-f623c12882d6.png)

**Comment by Aran30** [comment]
Should be kinda fixed once commit bd7a65907931ecbf381dbd2f6902ef8846116271 is merged.

The fix changes the following: if a file is sent, the message will be appended to the file message
![image](https://user-images.githubusercontent.com/50965489/147889747-30948334-c3a1-4be5-b365-aa3bce1cea51.png)
