### ISSUE TITLE
Feedbot saves statement in LRS but leaves out leading 0s of mail hashes

### ISSUE THREAD

**Issue by SandraSchufmann** [rwth-acis/las2peer-social-bot-manager-service#99]
When Feedbot saves student texts in the LRS, the hashed student mail addresses are missing leading 0s. 
(e.g. the hash beginning with 05abbc9... is saved as 5abbc9...)

**Comment by Aran30** [comment]
This is an issue regarding the [tmitocar wrapper service](https://github.com/rwth-acis/las2peer-tmitocar-service). A corresponding issue has been opened there: https://github.com/rwth-acis/las2peer-tmitocar-service/issues/9
